apiVersion: v1
kind: Service
metadata:
  name: enhanced-petclinic
  labels:
    app: enhanced-petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: enhanced-petclinic